adding two new options, custom filename and filename in output dir
bingryan/obsidian-markdown-export-plugin pull request #86
Opened 2024-06-28 22:07 UTC by shindakun

closes #85 

This PR will close #85, not sure if my code is up to snuff but it seems to work as expected. Putting up this PR just in case someone else wants a bit more control over the output like I did.

2024-06-28 23:53 UTC, bingryan commented
@shindakun thx for you pr, fix error plz 👍

2024-06-29 02:06 UTC, bingryan commented
@shindakun hi shindakun, can you merge latest master as first ?

2024-06-29 02:13 UTC, shindakun commented
> @shindakun hi shindakun, can you merge latest master as first ?

It should be as of the last commit.

2024-07-01 06:13 UTC, bingryan requested changes

2024-07-06 07:14 UTC, shindakun commented on src/main.ts
> +			path.join(this.settings.output, dir, this.settings.attachment),
So the files save into the correct directory if you have the option enabled

2024-07-07 06:03 UTC, bingryan approved these changes

2024-07-07 06:04 UTC, merged